name: 'Set up build dependencies'
description: 'Set up node, Gradle dependencies'
inputs:
  node-version:
    description: 'The required node version'
    required: true
    default: 16.14.0
  java-version:
    description: 'The required java version'
    required: true
    default: '11'
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: Install node.js packages
      shell: bash
      run: npm ci   
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ inputs.java-version }}
    - name: Cache local Gradle repository
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-